export const tools = [
  {
    "id": "001",
    "name": "String Util",
    "slug": "string-utils",
    "description": "Convert snake case, camel case, format",
    "url": "en/tool/001",
    "category": "tool-util",
    "thumbnail": "",
    "type": "link",
    "backgroundColor": "#EE1B2D",
    "textColor": "white"
  },
  {
    "id": "002",
    "name": "Extract data excel file",
    "slug": "extract-data-excel-file",
    "description": "Extract data excel file to json data",
    "url": "en/tool/002",
    "category": "tool-util",
    "thumbnail": "",
    "type": "link",
    "backgroundColor": "#EE1B2D",
    "textColor": "white"
  },
  {
    "id": "003",
    "name": "Translate data json i18n to another language",
    "slug": "translate-data-json-i18n-to-another-language",
    "description": "Translate data json i18n to another language",
    "url": "en/tool/003",
    "category": "tool-util",
    "thumbnail": "",
    "type": "link",
    "backgroundColor": "#EE1B2D",
    "textColor": "white"
  },
  {
    "id": "004",
    "name": "Convert String multiple line to String array",
    "slug": "convert-string-multiple-line-to-string-array",
    "description": "Convert String multiple line to String array",
    "url": "en/tool/004",
    "category": "tool-util",
    "thumbnail": "",
    "type": "link",
    "backgroundColor": "#EE1B2D",
    "textColor": "white"
  },
  {
    "id": "008",
    "name": "Call API Online tools",
    "slug": "call-api-online-tools",
    "description": "Call API Online tools",
    "url": "en/tool/008",
    "category": "tool-util",
    "thumbnail": "",
    "type": "link",
    "backgroundColor": "#EE1B2D",
    "textColor": "white"
  },
  {
    "id": "009",
    "name": "Search Param URL",
    "slug": "search-param-url",
    "description": "Convert URL has param to object JSON",
    "url": "en/tool/009",
    "category": "tool-util",
    "thumbnail": "",
    "type": "link",
    "backgroundColor": "#EE1B2D",
    "textColor": "white"
  },
  {
    "id": "011",
    "name": "Detect browser using javascript",
    "slug": "detect-browser-using-javascript",
    "description": "Detect browser using javascript",
    "url": "en/tool/011",
    "category": "tool-util",
    "thumbnail": "",
    "type": "link",
    "backgroundColor": "#EE1B2D",
    "textColor": "white"
  },
  {
    "id": "012",
    "name": "React Live",
    "slug": "react-live-coding",
    "description": "Coding react component online",
    "url": "en/tool/012",
    "category": "tool-util",
    "thumbnail": "",
    "type": "link",
    "backgroundColor": "#EE1B2D",
    "textColor": "white"
  },
  {
    "id": "014",
    "name": "Markdown live editor",
    "slug": "markdown-live-editor",
    "description": "Edit, preview markdown file on page",
    "url": "en/tool/014",
    "category": "tool-util",
    "thumbnail": "",
    "type": "link",
    "backgroundColor": "#EE1B2D",
    "textColor": "white"
  },
  {
    "id": "qr-core",
    "name": "QR Code JS",
    "slug": "qr-code-js",
    "description": "Create QR code which you want",
    "url": "en/tool/015",
    "thumbnail": "",
    "type": "link",
    "backgroundColor": "#EE1B2D",
    "textColor": "white"
  },
  {
    "id": "roadmap",
    "name": "Roadmap developer",
    "slug": "roadmap-developer",
    "description": "Frontend, Backend, DevOps, ReactJS, Android, Postgres",
    "url": "en/tool/016",
    "thumbnail": "",
    "type": "link",
    "backgroundColor": "#EE1B2D",
    "textColor": "white"
  },
  {
    "id": "ide",
    "name": "IDE Editor online",
    "slug": "ide-editor",
    "description": "IDE Editor online",
    "url": "en/tool/ide",
    "category": "tool-code",
    "thumbnail": "",
    "type": "link",
    "backgroundColor": "#EE1B2D",
    "textColor": "white"
  },
  {
    "id": "ide-monaco-editor",
    "name": "IDE Monaco Editor",
    "slug": "ide-monaco-editor",
    "description": "IDE Monaco Github",
    "url": "en/tool/ide-monaco-editor",
    "thumbnail": "",
    "type": "blank_link",
    "backgroundColor": "#EE1B2D",
    "textColor": "white"
  },
  {
    "id": "chat-with-ai",
    "name": "Chat with AI",
    "slug": "chat-with-ai",
    "description": "Chat with AI via Open AI API",
    "url": "en/tool/chat-with-ai",
    "thumbnail": "",
    "type": "blank_link",
    "backgroundColor": "#EE1B2D",
    "textColor": "white"
  },
  {
    "id": "image-generation-ai",
    "name": "Image generation",
    "slug": "image-generation",
    "description": "Get image generation by text",
    "url": "en/tool/image-generation",
    "thumbnail": "",
    "type": "blank_link",
    "backgroundColor": "#EE1B2D",
    "textColor": "white"
  }
]
